### ISSUE TITLE
Memoize text, html, json on response?

### ISSUE THREAD

**Issue by excid3** [rails/request.js#19]
I was playing with this today and noticed that a fetch response doesn't allow reading the body twice. To reproduce:

```javascript
const request = new FetchRequest("post", url)
const response = await request.perform()
await response.text
await response.text
// => Failed to execute 'text' on 'Response': body stream already read
```

And the situation that caught me was:
```javascript
const request = new FetchRequest("post", url, { responseKind: "turbo-stream" })
const response = await request.perform()
await response.text
// => Failed to execute 'text' on 'Response': body stream already read
```

A solution is that we could memoize the text, html, json getters so that you could call this multiple times.
```javascript
  get text () {
    return this.bodyText || (this.bodyText = this.response.text())
  }
```

I noticed this because I tried to read the text on a Turbo Stream response. Since `renderTurboStream` already accessed the text body, it seems unexpected.

Is this something worth fixing?

**Comment by ParamagicDev** [comment]
+1 not a bad idea. I just implemented this on mrujs without issues. Definitely weird bodies can only be consumed once. Im assuming its some weird limitation on ResponseStreams.

https://github.com/ParamagicDev/mrujs/pull/35/files

Anyways, figured id report it worked for me 🤷

**Comment by marcelolx** [comment]
@excid3 @ParamagicDev Yes, it's a good idea, I faced the same problem before extracting the package but didn't addressed the problem at the time.

**Comment by excid3** [comment]
Great, I'll get a PR started. 👍
