### ISSUE TITLE
Installing using esbuild on Rails 7

### ISSUE THREAD

**Issue by spaquet** [rails/request.js#43]
Is there an updated documentation to install request.js using esbuild? Rails 7 offers a neat option to remove webpacker and use esbuild.

So far, it seems that only import-map is offered in addition to Webpacker.

**Comment by spaquet** [comment]
Sorry, I confused this package with the gem...

**Comment by marcelolx** [comment]
I'm not familiar with esbuild, but can't you install the package in esbuild the same way you do with webpacker and only use esbuild to build it?
