### ISSUE TITLE
Multiselect is only sending the last selected option

### ISSUE THREAD

**Issue by luismoyano** [rails/request.js#52]
Hello!

Having a form with a multiselect where all the options are selected, only the last one is sent to the server.

How to reproduce:

- Have a form with a multiselect
- Add two or more options to it
- On a JS file pick that form using `FormData`
- Create a new request object with `new FetchRequest('get', 'a/url', {contentType: 'application/json', responseKind: 'json', data: yourFormData})`
- Call the `query` method with `yourFetchRequest.query`
- Notice the url params only include the last item in the multiselect

This happens on [utils.js](https://github.com/rails/request.js/blob/main/src/lib/utils.js#L39) on the merge entries method: The entries for a multiselect have identical keys looking similar to `my_model[my_multi_field][]` and different values which are deleted and replaced for the last one.

**Comment by marcelolx** [comment]
I think this PR fixed that https://github.com/rails/request.js/pull/50

**Comment by luismoyano** [comment]
Ah yes! I can see it now, I'm using request.js from npm directly, is there any chance to update it there or do I need to use the gem? (I'd rather not to)

**Comment by marcelolx** [comment]
btw, I just published v0.0.7 https://www.npmjs.com/package/@rails/request.js/v/0.0.7

**Comment by marcelolx** [comment]
can you test and see if it works? I'll close the issue, but let me know if the problem persists and we can work on a fix
