### ISSUE TITLE
Ability to set the option 'credentials'

### ISSUE THREAD

**Issue by Cervenka** [rails/request.js#55]
It may be useful to be able to set the option `credentials` to `include`.

At the moment it is hardcoded to `same-origin`.
https://github.com/rails/request.js/blob/main/src/fetch_request.js#L59

https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

Thank you

**Comment by Cervenka** [comment]
In my case I'm sending requests to a different subdomain (app.domain.com --> legacy-api.domain.com) - so cross origin.
legacy-api.domain.com's responds with the correct CORS headers.

I need the request to include the cookies that are shared across *.domain.com.
With the option set to `same-origin` the cookies are not included - similar to XHR calls with `withCredentials` set to false.

Thanks!

**Comment by marcelolx** [comment]
gotcha, thanks, I may have some time tomorrow to work on it.
