### ISSUE TITLE
Can shorthand methods be used not-async?

### ISSUE THREAD

**Issue by nimmolo** [rails/request.js#69]
To integrate a `requestjs` call with a complicated existing form on my site, I'd like to execute a `post` fetch non-async. Can the shorthand methods be used this way?

```js
post(url, { body: _formData, responseKind: "json" }).then((response) => {
  if (response.ok) {
    ...
  } else {
    ...
  }
}
```
It doesn't seem to work. Maybe there's a better way to do it. 

I'm using `requestjs` `post` in a stimulus controller for a form. It interrupts `submit` to upload files that have been added to a multi-file field, and add attachment records (very old app, not using ActiveStorage). These attachments will be associated with the "main" record that gets created when the form is `submit`ted. 

My form waits to submit until this `post` request has been called `x` number of times - as many times as there are file "attachments" - and a boolean flag in the Stimulus controller has been cleared. Each `post` request is adding a new "attachment" record that will be associated with the "main" record that gets created on `submit`.

When the `post` is async, the form submits prematurely; the attachments do not exist yet, and they are not associated with the "main" record, or the "main" record is created twice - once without attachments, and once with.

**Comment by nimmolo** [comment]
@marcelolx it was a different problem causing the premature submit. 
I checked everything for hours before posting this, but i missed something!! 

Sorry, thanks for confirming it should work with `.then((response) =>{})`

**Comment by marcelolx** [comment]
Perfect, glad you figured it out!
