### ISSUE TITLE
sameHost check with https: urls

### ISSUE THREAD

**Issue by finchi** [rails/request.js#80]
Hello,

I encountered an issue with a CDN that blocked the `x-csrf-token` header. Since the CDN and the requesting site have different hostnames, I was initially confused about where the problem was originating.

After reviewing the code, I found the following line and was wondering why `https:` is not included here:
https://github.com/rails/request.js/blob/f3460a124576312be4f21d1c1c753adb99f2f651/src/fetch_request.js#L52

Is this an oversight, or is there another reason for omitting `https:`?

**Comment by marcelolx** [comment]
Probably an oversight @t27duck?

Related PR https://github.com/rails/request.js/pull/46

**Comment by t27duck** [comment]
https://github.com/rails/request.js/pull/81 should do it

**Comment by marcelolx** [comment]
Thanks @t27duck

**Comment by finchi** [comment]
@t27duck thanks for the quick fix 👏
