### ISSUE TITLE
shorthand methods : get, post, put, delete

### ISSUE THREAD

**Issue by adrienpoly** [rails/request.js#9]
This package looks promising as a replacement for the good old Rails.ajax

I would suggest to provide, in addition to the Class base request constructor some shorthand version for the 4 main verbs

so that we could write the example like that 

```js
import { post } from '@rails/request.js'

....

async myMethod () {
  const response = await post('localhost:3000/my_endpoint', { body: { name: 'Request.JS' }}))
  if (response.ok) {
    const body = await response.text
    // Do whatever do you want with the response body
    // You also are able to call `response.html` or `response.json`, be aware that if you call `response.json` and the response contentType isn't `application/json` there will be raised an error.
  }
}
```

For me, this would feel more idiomatic 

implementation could be something like

```js
async post = (url, options) {
  const request = new Request('post', url, options)
  return request.perform()
}
```

I can submit a PR if this is of interest

**Comment by marcelolx** [comment]
@adrienpoly The idea looks good to me, feel free to send a PR.

**Comment by excid3** [comment]
This would be handy. 👍
